### ISSUE TITLE
works only on mac. and forces specific platform setting.

### ISSUE THREAD

**Issue by rcherukuri12** [kongzii/SwiftXGBoost#10]
Hi,
I found that the library is fixed to work only on mac. 
Is there any way you can make it work on both mac and ubuntu ?

**Comment by kongzii** [comment]
Hi, I am using it on Ubuntu (18.04) without any problems, and it is also tested against ubuntu (https://github.com/kongzii/SwiftXGBoost/actions?query=workflow%3AUbuntu). Can you share error?

**Comment by rcherukuri12** [comment]
Here is the error I get, if I don't have the platform syntax in Package.swift


error: the executable 'xgb_tuner' requires macos 10.10, but depends on the product 'XGBoost' which requires macos 10.13; consider changing the executable 'xgb_tuner' to require macos 10.13 or later, or the product 'XGBoost' to require macos 10.10 or earlier.

I am using toolchain from swift4TF 0.10 release.

It gets fixed if I add:
platforms: [.macOS(.v10_13),],

Also, I picked up the above information from
https://github.com/kongzii/SwiftXGBoost/blob/master/Package.swift


Regards

Raja C.


________________________________

**Comment by kongzii** [comment]
Yes, SwiftXGBoost requires `macOS 10.13+` and if you want to use it in your application, you need to specify that you require `macOS 10.13+` as well. So that is why you need to add 

```swift
platforms: [.macOS(.v10_13),],
```

in your `Package.swift`. However, it has no impact on Ubuntu users. It's like, "if you are using macOS, it needs to be 10.13+, if you are using Ubuntu, you are OK".
